# Generated by Django 5.2.16 on 2026-07-17 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content', to='courses.course'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_content', to='lessons.lesson'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['student', 'is_active'], name='ai_chatsess_student_f94c32_idx'),
        ),
    ]
