# Generated by Django 5.2.16 on 2026-07-17 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('duration_hours', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdfs/')),
                ('is_verified', models.BooleanField(default=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoke_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='certificates/templates/')),
                ('logo', models.ImageField(blank=True, upload_to='certificates/logos/')),
                ('signature', models.ImageField(blank=True, upload_to='certificates/signatures/')),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('signature_title', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
